version: '3.8'

services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"  # Mở cổng 80 cho người dùng truy cập
    volumes:
      # Gắn file cấu hình mình vừa tạo vào trong container
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    image: example-frontend
    build: ./example-frontend
    environment:
      # SỬA: Trỏ vào đường dẫn API qua Nginx
      - REACT_APP_BACKEND_URL=http://localhost/api

  backend:
    image: example-backend
    build: ./example-backend
    environment:
      # SỬA: Cho phép truy cập từ trang chủ (Nginx)
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - db

  redis:
    image: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./database:/var/lib/postgresql/data