services:
  backend:
    image: example-backend
    build: ./example-backend  # <--- Thêm dòng này (Trỏ vào thư mục code backend)
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5001

  frontend:
    image: example-frontend
    build: ./example-frontend # <--- Thêm dòng này (Trỏ vào thư mục code frontend)
    ports:
      - "5001:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

# Vào example-2.6 để chạy docker-compose up --build